[phases.setup]
nixPkgs = ["python312", "gcc", "pkg-config", "freetype", "libjpeg", "zlib", "postgresql"]
aptPkgs = ["libfreetype6", "libfreetype6-dev", "libjpeg-dev", "libwebp-dev", "zlib1g-dev", "libpq-dev"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"

[variables]
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/usr/local/lib:/nix/var/nix/profiles/default/lib"
LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/usr/local/lib"
PYTHONPATH = "/app"

# Explicitly define the worker for Nixpacks
[processes]
web = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
worker = ". /opt/venv/bin/activate && celery -A config worker --loglevel=info"
