# Generated by Django 6.0.3 on 2026-06-28 05:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0027_deliveryguyweeklypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daraja_consumer_key', models.CharField(max_length=200)),
                ('daraja_consumer_secret', models.CharField(max_length=200)),
                ('daraja_shortcode', models.CharField(max_length=20)),
                ('daraja_passkey', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='deliveryguyweeklypayment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='deliveryguyweeklypayment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_guy',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='order',
            name='review',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category_fkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='urbanfoods.foodcategory'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_window_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='eta_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='google_maps_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rating_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='order',
            name='review_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_base_fare',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='acceptance_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('partner', 'Partner'), ('rider', 'Rider'), ('superadmin', 'Super Admin')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryguyweeklypayment',
            name='deliveries_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryguyweeklypayment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryguyweeklypayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryguyweeklypayment',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryguyweeklypayment',
            name='week_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deliveryguyweeklypayment',
            name='week_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(blank=True, choices=[('whisky', 'Whisky'), ('wine', 'Wine'), ('beer', 'Beer'), ('gin', 'Gin'), ('spirits', 'Spirits'), ('champagne', 'Champagne')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='hostel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='review_prompt_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='review_prompted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned to Rider'), ('picked_up', 'Picked Up'), ('arrived', 'Rider Arrived'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
        migrations.CreateModel(
            name='RiderEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='urbanfoods.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiderLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urbanfoods.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_radius_km', models.IntegerField(default=7)),
                ('shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subdomain', models.SlugField(blank=True, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='store_covers/')),
                ('primary_color', models.CharField(default='#F97316', max_length=7)),
                ('secondary_color', models.CharField(default='#1F2937', max_length=7)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('rating_count', models.IntegerField(default=0)),
                ('avg_delivery_minutes', models.IntegerField(default=30)),
                ('is_open', models.BooleanField(default=True)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('base', 'Base'), ('pro', 'Pro'), ('custom', 'Custom')], default='base', max_length=20)),
                ('plan_price', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('subscription_active', models.BooleanField(default=False)),
                ('subscription_expires', models.DateField(blank=True, null=True)),
                ('billing_status', models.CharField(choices=[('active', 'Active'), ('grace_period', 'Grace Period'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_expiry_reminder_sent', models.DateField(blank=True, null=True)),
                ('payhero_username', models.CharField(blank=True, max_length=200, null=True)),
                ('payhero_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('payhero_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rider_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_rating', to='urbanfoods.order')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_ratings', to='urbanfoods.store')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urbanfoods.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urbanfoods.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='urbanfoods.store'),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='urbanfoods.store')),
            ],
        ),
    ]
