# Generated by Django 6.0.3 on 2026-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0031_store_delivery_fee_alter_store_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='flutterwave_currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='flutterwave_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='flutterwave_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='flutterwave_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='flutterwave_webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_provider',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('manual', 'Manual')], default='flutterwave', max_length=20),
        ),
    ]
