# Generated by Django 6.0.3 on 2026-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0032_store_flutterwave_currency_store_flutterwave_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_stores',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='urbanfoods.store'),
        ),
    ]
