# Generated by Django 6.0.3 on 2026-07-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0034_user_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
