# Generated by Django 6.0.3 on 2026-07-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0035_store_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
