# Generated by Django 6.0.3 on 2026-07-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0036_fooditem_is_new_arrival_store_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='flutterwave_currency',
        ),
        migrations.RemoveField(
            model_name='store',
            name='flutterwave_enabled',
        ),
        migrations.RemoveField(
            model_name='store',
            name='flutterwave_public_key',
        ),
        migrations.RemoveField(
            model_name='store',
            name='flutterwave_secret_key',
        ),
        migrations.RemoveField(
            model_name='store',
            name='flutterwave_webhook_secret',
        ),
        migrations.RemoveField(
            model_name='store',
            name='payhero_account_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='payhero_api_key',
        ),
        migrations.RemoveField(
            model_name='store',
            name='payhero_username',
        ),
        migrations.RemoveField(
            model_name='store',
            name='payment_provider',
        ),
        migrations.AddField(
            model_name='store',
            name='mpesa_callback_url',
            field=models.URLField(blank=True, help_text='Store-specific callback URL', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mpesa_consumer_key',
            field=models.TextField(blank=True, help_text='Encrypted Consumer Key', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mpesa_consumer_secret',
            field=models.TextField(blank=True, help_text='Encrypted Consumer Secret', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mpesa_passkey',
            field=models.TextField(blank=True, help_text='Encrypted Passkey', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, help_text='Business Short Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='daraja_consumer_key',
            field=models.TextField(help_text='Encrypted Consumer Key'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='daraja_consumer_secret',
            field=models.TextField(help_text='Encrypted Consumer Secret'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='daraja_passkey',
            field=models.TextField(help_text='Encrypted Passkey'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='daraja_shortcode',
            field=models.CharField(max_length=50),
        ),
    ]
