# Generated by Django 6.0.3 on 2026-07-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0037_remove_store_flutterwave_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingBlast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('target_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blasts', to='urbanfoods.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
