# Generated by Django 6.0.3 on 2026-07-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0038_marketingblast'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='base_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Fee for base distance', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='base_distance_km',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Distance covered by base fee', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='extra_distance_surcharge',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Charge per extra KM', max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='base_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='base_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='extra_distance_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Legacy global fee', max_digits=10),
        ),
    ]
