# Generated by Django 6.0.3 on 2026-07-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0040_promotion_store_alter_promotion_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requires_rider_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_verification_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_age_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Calculated risk score (0-100)'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Silent sentry behavior signals'),
        ),
    ]
