# Generated by Django 6.0.3 on 2026-07-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0041_order_requires_rider_verification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='subscription_active',
        ),
        migrations.AddField(
            model_name='order',
            name='verification_image',
            field=models.FileField(blank=True, null=True, upload_to='verifications/'),
        ),
    ]
