# Generated by Django 6.0.3 on 2026-07-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0043_alter_fooditem_description_alter_fooditem_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRevenueStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_liquor_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('partner_share_40', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_stats', to='urbanfoods.store')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('store', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='PartnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mpesa_code', models.CharField(max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='urbanfoods.store')),
                ('week_stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='urbanfoods.weeklyrevenuestat')),
            ],
        ),
    ]
