# Generated by Django 6.0.3 on 2026-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0044_weeklyrevenuestat_partnerpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrevenuestat',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyrevenuestat',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Legacy field, use status instead'),
        ),
    ]
