# Generated by Django 6.0.3 on 2026-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0047_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
