# Generated by Django 6.0.3 on 2026-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0048_cart_last_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='accepts_wallet_payments',
            field=models.BooleanField(default=True),
        ),
    ]
