# Generated by Django 6.0.3 on 2026-07-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0049_order_wallet_used_store_accepts_wallet_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Custom commission rate for Enterprise partners', max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='is_franchise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='parent_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='urbanfoods.store'),
        ),
    ]
