# Generated by Django 6.0.3 on 2026-07-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0057_panicalert_riderweeklystat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirikicontribution',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
