# Generated by Django 6.0.3 on 2026-07-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0058_alter_shirikicontribution_checkout_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirikicontribution',
            name='amount_applied_to_pot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shirikicontribution',
            name='wallet_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
