# Generated by Django 6.0.3 on 2026-08-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0059_shirikicontribution_amount_applied_to_pot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Monthly Subscription'), ('commission', 'Pay As You Go Commission')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='week_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='urbanfoods.weeklyrevenuestat'),
        ),
        migrations.AlterField(
            model_name='store',
            name='plan',
            field=models.CharField(choices=[('free', 'Free (Pay As You Go)'), ('base', 'Base'), ('pro', 'Pro'), ('custom', 'Custom')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
