# Generated by Django 6.0.3 on 2026-08-20 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0060_subscriptionpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa')], default='mpesa', max_length=20)),
                ('payment_type', models.CharField(choices=[('order', 'Order'), ('subscription', 'Subscription'), ('shiriki', 'Shiriki Contribution'), ('commission', 'Commission')], max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('initiating', 'Initiating'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired'), ('manual_review', 'Manual Review'), ('overpaid', 'Overpaid'), ('refund_required', 'Refund Required')], db_index=True, default='initiating', max_length=20)),
                ('provider_result_code', models.IntegerField(blank=True, null=True)),
                ('provider_result_description', models.TextField(blank=True)),
                ('failure_code', models.CharField(blank=True, max_length=50)),
                ('failure_message', models.TextField(blank=True)),
                ('raw_initiation_response', models.JSONField(blank=True, null=True)),
                ('raw_callback_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('initiation_started_at', models.DateTimeField(blank=True, null=True)),
                ('initiation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='urbanfoods.order')),
                ('shiriki_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='urbanfoods.shirikicontribution')),
                ('subscription_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='urbanfoods.subscriptionpayment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallbackInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_hash', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa')], default='mpesa', max_length=20)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('retry', 'Retry'), ('unmatched', 'Unmatched'), ('manual_review', 'Manual Review')], db_index=True, default='received', max_length=20)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('payment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_events', to='urbanfoods.paymentattempt')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['status', 'created_at'], name='payment_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['payment_type', 'status'], name='payment_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['order', 'status'], name='payment_order_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_request_id__isnull', False)), fields=('provider', 'checkout_request_id'), name='uniq_payment_provider_checkout'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_receipt__isnull', False)), fields=('provider', 'provider_receipt'), name='uniq_payment_provider_receipt'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(check=models.Q(('order__isnull', False), ('subscription_payment__isnull', False), ('shiriki_contribution__isnull', False), _connector='XOR'), name='payment_attempt_one_target'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(check=models.Q(('expected_amount__gt', 0)), name='payment_attempt_positive_expected_amount'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(check=models.Q(('received_amount__isnull', True), ('received_amount__gte', 0), _connector='OR'), name='payment_attempt_nonnegative_received_amount'),
        ),
        migrations.AddIndex(
            model_name='callbackinbox',
            index=models.Index(fields=['status', 'received_at'], name='callback_status_received_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackinbox',
            index=models.Index(fields=['provider', 'checkout_request_id'], name='callback_provider_checkout_idx'),
        ),
    ]
