# Generated by Django 6.0.3 on 2026-08-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0061_payment_attempt_callback_inbox'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentattempt',
            name='payment_attempt_one_target',
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order__isnull', False), ('subscription_payment__isnull', True), ('shiriki_contribution__isnull', True)), models.Q(('order__isnull', True), ('subscription_payment__isnull', False), ('shiriki_contribution__isnull', True)), models.Q(('order__isnull', True), ('subscription_payment__isnull', True), ('shiriki_contribution__isnull', False)), _connector='OR'), name='payment_attempt_one_target'),
        ),
    ]
