# Generated by Django 6.0.3 on 2026-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0062_fix_payment_attempt_target_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shirikicontribution',
            name='payment_idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
