# Generated by Django 6.0.3 on 2026-08-20 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0066_order_revenue_share_applied_at_outboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='manual_review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='next_reconciliation_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='reconciliation_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='reconciliation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('failed', 'Failed'), ('pending', 'Pending'), ('error', 'Error'), ('manual_review', 'Manual Review')], max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='urbanfoods.paymentattempt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_attempt', 'created_at'], name='recon_attempt_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('payment_attempt', 'attempt_number'), name='uniq_reconciliation_attempt_number')],
            },
        ),
    ]
