# Generated by Django 6.0.3 on 2026-08-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0067_paymentattempt_manual_review_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('finalized', 'Finalized')], db_index=True, default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='urbanfoods.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='urbanfoods.order')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'reserved_at'], name='inv_res_status_reserved_idx'), models.Index(fields=['food_item', 'status'], name='inv_res_food_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'food_item'), name='uniq_inventory_reservation_order_item'), models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='inventory_reservation_positive_quantity')],
            },
        ),
    ]
