# Generated by Django 6.0.3 on 2026-08-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0068_inventoryreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_redemption', to='urbanfoods.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='urbanfoods.promotion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('promotion', 'order'), name='uniq_promotion_order_redemption')],
            },
        ),
    ]
