# Generated by Django 6.0.3 on 2026-08-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0069_promotionredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
