# Generated by Django 6.0.3 on 2026-08-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0070_order_idempotency_fingerprint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shirikicontribution',
            index=models.Index(fields=['session', 'status', 'created_at'], name='shiriki_contrib_state_idx'),
        ),
        migrations.AddIndex(
            model_name='shirikisession',
            index=models.Index(fields=['status', 'expires_at'], name='shiriki_sess_status_exp_idx'),
        ),
    ]
