# Generated by Django 6.0.3 on 2026-08-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0071_shirikicontribution_shiriki_contrib_state_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='callbackinbox',
            index=models.Index(fields=['status', 'next_attempt_at'], name='callback_status_next_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['status', 'checkout_request_id'], name='payment_status_checkout_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['status', 'next_reconciliation_at'], name='payment_status_next_recon_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['store', 'code', 'is_active'], name='promo_store_code_active_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['store', 'is_active', 'start_date', 'end_date'], name='promo_store_active_dates_idx'),
        ),
    ]
