# Generated by Django 6.0.3 on 2026-08-24 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0074_encryption_at_rest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('failed_velocity', 'Failed Attempt Velocity'), ('unusual_amount', 'Unusual Amount'), ('test_transactions', 'Test Transactions'), ('order_velocity', 'Order Velocity'), ('geographic_anomaly', 'Geographic Anomaly'), ('rate_limit_bypass', 'Rate Limit Bypass'), ('callback_manipulation', 'Callback Manipulation')], db_index=True, max_length=30)),
                ('confidence', models.FloatField(db_index=True, help_text='Confidence score (0.0-1.0). Auto-blocked at 75%+ confidence.')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('phone_number', models.CharField(help_text='Phone number used in fraudulent attempt', max_length=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('escalated', 'Escalated to Authorities'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], db_index=True, default='open', max_length=30)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Pattern-specific details (e.g., attempt count, amount, IP, timestamp)')),
                ('investigation_notes', models.TextField(blank=True, help_text='Investigation findings and actions taken')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_phone_encrypted_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_phone_encrypted_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payment_aud_admin_u_5bab20_idx',
            old_name='payment_audi_admin_u_012345_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payment_aud_object__14f977_idx',
            old_name='payment_audi_object__012345_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payment_aud_action_403688_idx',
            old_name='payment_audi_action__012345_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone_encrypted',
            field=models.TextField(blank=True, help_text='🛡️ Encrypted customer phone (ENCRYPTED: prefix). Read via EncryptedFieldManager.', null=True),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='phone_number_encrypted',
            field=models.TextField(blank=True, help_text='🛡️ Encrypted M-Pesa phone (ENCRYPTED: prefix). Read via EncryptedFieldManager.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_encrypted',
            field=models.TextField(blank=True, help_text='🛡️ Encrypted email (ENCRYPTED: prefix). Read via EncryptedFieldManager.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_encrypted',
            field=models.TextField(blank=True, help_text='🛡️ Encrypted phone number (ENCRYPTED: prefix). Read via EncryptedFieldManager.', null=True),
        ),
        migrations.AddField(
            model_name='fraudincident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Security team member investigating this incident', limit_choices_to={'role': 'superadmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fraud_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudincident',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer associated with fraud pattern', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudincident',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order associated with fraud (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_incidents', to='urbanfoods.order'),
        ),
        migrations.AddIndex(
            model_name='fraudincident',
            index=models.Index(fields=['customer', 'status'], name='fraud_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudincident',
            index=models.Index(fields=['created_at', 'severity'], name='fraud_time_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudincident',
            index=models.Index(fields=['pattern_type', 'confidence'], name='fraud_pattern_confidence_idx'),
        ),
    ]
