# Generated by Django 4.2.7 on 2026-09-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0076_supportticket_supportmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='mpesa_transaction_type',
            field=models.CharField(choices=[('CustomerPayBillOnline', 'Paybill'), ('CustomerBuyGoodsOnline', 'Till/Buy Goods')], default='CustomerPayBillOnline', max_length=30),
        ),
    ]
