# Generated by Django 4.2.7 on 2026-09-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0077_store_mpesa_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='mpesa_till_number',
            field=models.CharField(blank=True, help_text='Required for Buy Goods transactions', max_length=20, null=True),
        ),
    ]
